{% set name = "blacken-docs" %}
{% set version = "1.17.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 06b8404eac3f51518d0ebc6abe4c4e96bde880cdfa2cc53ed16548f86eee5395

build:
  number: 0
  noarch: python
  entry_points:
    - blacken-docs=blacken_docs:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - black >=19.3b0
    - python >=3.6

test:
  imports:
    - blacken_docs
  commands:
    - pip check
    - blacken-docs --help
  requires:
    - pip

about:
  home: https://github.com/asottile/blacken-docs
  summary: Run `black` on python code blocks in documentation files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
