{% set name = "blacken-docs" %}
{% set version = "1.20.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 2d5b6caf6e7da5694b1eba97f9132c1ab9f14f221c82205ec473a6e74fbb2c6d

build:
  number: 0
  noarch: python
  entry_points:
    - blacken-docs=blacken_docs:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - black >=22.1
    - python >={{ python_min }}

test:
  imports:
    - blacken_docs
  commands:
    - pip check
    - blacken-docs --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/asottile/blacken-docs
  summary: Run `black` on python code blocks in documentation files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
