{% set name = "blacken-docs" %}
{% set version = "1.19.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
  sha256: 3cf7a10f5b87886683e3ab07a0dc17de41425f3d21e2948e59f1c6079c45b328

build:
  number: 0
  noarch: python
  entry_points:
    - blacken-docs=blacken_docs:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - black >=22.1
    - python >=3.9

test:
  imports:
    - blacken_docs
  commands:
    - pip check
    - blacken-docs --help
  requires:
    - pip

about:
  home: https://github.com/asottile/blacken-docs
  summary: Run `black` on python code blocks in documentation files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xhochy
